name: CI Pipeline - Simulador SFN

# Define QUANDO a esteira vai rodar
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código (Checkout)
      uses: actions/checkout@v4

    - name: Configurar o ambiente (Node.js)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependências
      run: npm install

    - name: Rodar Testes Unitários do Domínio
      run: npm run test

    - name: Validar a Compilação do Projeto (Build)
      run: npm run build
      env:
        DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"